name: Deploy to server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'asyomei/himawari'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy
        env:
          SSH_DEST: ${{ secrets.SSH_DEST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
          ALWAYS_KEY: ${{ secrets.ALWAYS_KEY }}
          ALWAYS_ACCOUNT: ${{ secrets.ALWAYS_ACCOUNT }}
          ALWAYS_SERVICE_ID: ${{ secrets.ALWAYS_SERVICE_ID }}
        run: bash deploy.sh
